name: build_n_run
on: [push]
jobs:
    build_n_run:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: sudo apt-get update && sudo apt-get install -y cmake
          - run: mkdir build && cmake -B build -S . && cmake --build build 
          - uses: actions/upload-artifactv4
            with:
              name: binaries
              path: |
                build/main
                build/tests
    tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifactv4
            with:
              name: binaries
          - run: chmod +x tests && ./tests
    
    run:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/download-artifactv4
            with:
              name: binaries
          - run: chmod +x main && ./main 2 7