name: build_n_run
on: [push]
jobs:
    build_n_run:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: g++ main.cpp my_add.cpp -o main
          - run: ./main 4 6